### ISSUE TITLE
Is there a way to get the database writer plugin to work with version 3 (linux if it matters) 

### ISSUE THREAD

**Issue by gariac** [vradarserver/vrs#121]
I get an incompatibility message.

https://imgur.com/a/Lk7p7sp

**Comment by vradarserver** [comment]
Download and install version 3 of the plugin. As of time of writing it's here:

https://github.com/vradarserver/vrs/releases/tag/v3.0.0-preview-11-mono

**Comment by gariac** [comment]
> Download and install version 3 of the plugin. As of time of writing it's here:
> 
> https://github.com/vradarserver/vrs/releases/tag/v3.0.0-preview-11-mono

I'm not sure this reply will go though or not since the issue is closed.  I don't know how I missed this page but have now bookmarked it.
