### ISSUE TITLE
Use VRS offline

### ISSUE THREAD

**Issue by begleysm** [vradarserver/vrs#13]
Is there a way to use VRS offline?  Having a basemap would be ideal but even mapless would be better than nothing.

**Comment by vradarserver** [comment]
You can use the tile server cache plugin while online to cache map tiles. The plugin should then serve cached tiles while you are offline.

https://old.reddit.com/r/virtualradarserver/comments/bzwljc/preview_installers_last_updated_on_12jun2019/

**Comment by begleysm** [comment]
Thank you!

**Comment by begleysm** [comment]
For anyone stumbling across this Issue thread.  I've got my Virtual Radar Server working how I want.  I have offline mapping capability but instead of using the Tile Server Cache Plugin I chose to roll my own local Open Street Maps Tile Server and then have VRS point to that Tile Server for getting its background maps.

You can read my How To writeup for creating your own Open Street Maps Tile Server here
https://steamforge.net/wiki/index.php/Creating_How_to_Setup_an_Open_Street_Map_Tile_Server_under_Ubuntu_18.04_in_a_Proxmox_Container

You can read my How To writeup on installing Virtual Radar Server (under Linux) and configuring it to use my local Open Street Maps Tile Server here
https://steamforge.net/wiki/index.php/How_to_setup_Virtual_Radar_Server_and_pingStation_for_offline_use#Target_your_Local_OSM_Tile_Server

The major piece of info that I had trouble finding is how to add our local Tile Server to the WebAdmin Tile server drop down.  The info was hard to find on Google but is located at
https://github.com/vradarserver/vrs/blob/master/VirtualRadar.Localisation/Content/TileServerSettings-ReadMe.txt
or locally on your machine (after installing VRS in Linux) at ~/.local/share/VirtualRadar/TileServerSettings-ReadMe.txt

**Comment by KoPhyo777** [comment]
> at I had trouble finding is how to add our local Tile Server to the WebAdmin Tile server drop down. The info was hard to find on Google but is located at



> You can use the tile server cache plugin while online to cache map tiles. The plugin should then serve cached tiles while you are offline.
> 
> https://old.reddit.com/r/virtualradarserver/comments/bzwljc/preview_installers_last_updated_on_12jun2019/

how about client can receive offline map
