### ISSUE TITLE
Use of SDM data in third party applications

### ISSUE THREAD

**Issue by Niall7459** [vradarserver/vrs#27]
Hello,

What are your terms and conditions on using SDM data in third party applications. Of course if this is not permitted at all I will refrain from using it.

I would stick to the defined MinSeconds, MaxBatchSize etc defined in the settings XML endpoint.

Many thanks

**Comment by vradarserver** [comment]
It depends. I don't have a problem with you using anything that's in the SDM file that gets downloaded (routes, airports, airlines, model types etc.) but just to be clear you must not use it for anything important. There are mistakes in the data and it is always going to be somewhat out of date. That goes for all data exposed by the SDM site.

Regarding the aircraft lookup, the data there isn't mine. I'm using Planebase's data. If Planebase are OK with you using the SDM site to look up aircraft data then I don't mind as long as you stick to the batch limits etc., and keep in mind that there are rate limits in force on the aircraft lookup service... but you'd need to check with them to see if they care.

**Comment by Niall7459** [comment]
Thank you for the response. I'm aware all data is inaccurate and their likely mistakes or older data. I'll check out the SDM file that get's downloaded.

Thank you.
