### ISSUE TITLE
libpng warnings under some Linux distros

### ISSUE THREAD

**Issue by vradarserver** [vradarserver/vrs#36]
The version of libpng used by some Linux distros complains about some of the PNGs that ship with VRS (all versions):

```
libpng warning: iccp known incorrect sRGB profile
libpng warning: cHRM chunk does not match sRGB
```

Google seems to think that running PNGs through a utility that comes with ImageMagick should strip off the unwanted cHRM chunk without ill-effect:

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile/29337595#29337595

**Comment by mypiaware** [comment]
I did the following to keep the 'libpng warning' messages from appearing in 2.4.4 as there appears to be several problems with two of the PNG marker files.  Problems: (1) The images have the wrong filenames. (2) The images need to have their color space converted.  What I did is the following:

1. Made a copy of each of these two images:
        `Web/images/markers/Marker_Airplane.png`
	`Web/images/markers/Marker_AirplaneSelected.png`
2. Renamed each of the two copies as such:
 	`Marker_Airplane.png` to `Airplane.png`
	`Marker_AirplaneSelected.png` to `AirplaneSelected.png`
3. Converted the color space of each of these two files. (ImageMagick was only successful with one of the two PNG files, so I used GIMP on both of them.)
4. Used Custom Content Plugin to have VRS use the new PNG marker files.
	- Created an `images/markers` directory at my "Site root folder" location.
	- Placed the two new PNG marker files in the `<Site root folder>/images/markers` directory.

**Comment by vradarserver** [comment]
@mypiaware The images have the correct filenames, it's just that there are two copies of them. One lives in the markers folder and the other is compiled into the application's executable. The versions in the executable are called `Airplane.png` and `AirplaneSelected.png` and those are the ones that you're overriding with local copies.

That said, you are correct about those two being the culprits that libpng is complaining about. Thanks for letting me know.

**Comment by vradarserver** [comment]
V2: 43fbbe0
V3: 1b86db2
