### ISSUE TITLE
Feature Request: Additional List Link

### ISSUE THREAD

**Issue by dxmekch** [vradarserver/vrs#5]
Is it possible to add a hyperlink to the aircraft list which refers to jetphotos.net? I asked myself the question why do we need this extra url - jetphotos is the most "up to date" database since a few years.

The url would be:
https://www.jetphotos.com/photo/keyword/ `append Registration or Serial Number here`

For example:
https://www.jetphotos.com/photo/keyword/P4-MES

I'd prefer the registration. Take care as it is necessary to include the dash in the url for searching similar to the airliners.net url.

Thanks! 
Dominik

**Comment by mguinness** [comment]
Looking at the source, it appears that you could just create another LinkRenderHandler entry.

https://github.com/vradarserver/vrs/blob/665f99ba2c6a670a0ca95f334a4924168a7cf5e6/VirtualRadar.WebSite/Site/Web/script/vrs/linksRenderer.ts#L138-L146

**Comment by vradarserver** [comment]
Replaced the link to airframes.org (which now requires login credentials) with a link to jetphotos.com.

V3 commit: 6c488e0
V2 commit: 00d774a
