### ISSUE TITLE
Find a new source for embedded thumbnails.

### ISSUE THREAD

**Issue by bfayers** [vradarserver/vrs#54]
The removal of thumbnails using airport-data.com (09d3f72) is a great feature which I miss in the newest previews.

I am wondering if a new source for images could be found? [Airliners.net](https://airliners.net) and [JetPhotos.com](https://jetphotos.com) have large amounts of images available, though seem to be lacking APIs.

**Comment by vradarserver** [comment]
If you ever find one then let me know. As you mention, airliners.net and jetphotos don't have freely available APIs and I don't want to scrape web pages for thumbnails.

If you want to continue using airport-data.com thumbnails then there is a plugin that puts them back, it can be found here:

Windows: https://github.com/vradarserver/vrs-other-plugins/releases/tag/latest-airportdata-thumbnails-windows
Mono: https://github.com/vradarserver/vrs-other-plugins/releases/tag/latest-airportdata-thumbnails-mono

Use at your own risk.

**Comment by bfayers** [comment]
Ah thanks. If I do find another source I'll probably open a PR; didn't notice the plugin - thanks for the link

**Comment by avgeeklucky** [comment]
planespotters.net has an API: https://www.planespotters.net/photo/api
