### ISSUE TITLE
3.0.0 Release 10 Reports Pages No Longer Have Database Edit Link

### ISSUE THREAD

**Issue by gonzalu** [vradarserver/vrs#84]
Looks like the report page is not rendering the Database Edit link in the details section. Likns to Airliners.net and Jetphotos.net are the only ones showing up.

I looked at the HTML and it is linking the same Links Handler as the main Desktop page. Not sure if this is something I can fix on my own and needs a new Beta. 

Thank you!

**Comment by dziban303** [comment]
Anyone have ideas on how to put together a temporary solution for this? The workflow for adding details is sort of cumbersome without the link there. Not a deal-breaker by any means, just adds a bunch of clicks and copypasting. I would really appreciate any suggestions!

**Comment by vradarserver** [comment]
I'm sorry to say that I got distracted and forgot about this :) I do apologise. Preview 11 should fix the issue, if you're looking to take a shortcut then you only need to download the server if you've already got preview 10 installed.
