### ISSUE TITLE
CodeBlock Overrides

### ISSUE THREAD

**Issue by Datamix** [vradarserver/vrs#87]
Hi, I'm currently using VRS 3 Preview 10.

I use the CodeBlock Overrides as described in the documentation:

[China]
899160 civ		# B-18912

However, the log says "civ" is invalid. See error message below.

[2023-01-07 11:58:56.131 UTC] [t1] Invalid military/civilian designator 'civ' - must be one of 'mil' or 'civ' at line 48 of local codeblock override

The "mil" designator does not trigger an error.

Any ideas? Worked like this in the preceding versions.

Thank you

**Comment by rikgale** [comment]
See the closed #81 
Should work in the next release.
