### ISSUE TITLE
What happened to the receiver range option?

### ISSUE THREAD

**Issue by jepolch** [vradarserver/vrs#90]
I installed VRS beta 3 and I don't see "receiver range" under options in the web interface as I do in VRS 2.4.4. Thank you.

**Comment by vradarserver** [comment]
It's the first option under Raw Feed Decoding. I don't think it changed between v2 and v3.

**Comment by Wyehoota** [comment]
See #125 - I have observed "receiver range" display and options disappear if you connect to the server via ipv6. If you want it back, ensure you access via ipv4 port.
